FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
COPY .env.prod ./.env
COPY gunicorn.conf.py ./gunicorn.conf.py

ENV PRODUCTION="prod" PORT=8001

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app.main:app"]